name: Generar PDF desde README

on:
  push:
    branches: [ main ]
    paths:
      - "README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Crear carpeta generados
        run: mkdir -p docs/generados

      - name: Convertir Markdown a PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: docs/generados
          build_html: false

      - name: Ver qué se generó
        run: |
          ls -lah docs/generados
          git status --porcelain

      - name: Commit y push del PDF
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add docs/generados/*.pdf
          git diff --cached --quiet && echo "No hay cambios" && exit 0
          git commit -m "docs: actualizar PDF del README"
          git push
